Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/focal64"                          # boxes at https://vagrantcloud.com/search.
  config.vm.network "forwarded_port", guest: 80, host: 8080 # Create a forwarded port mapping which allows access to a specific port within the machine from a port on the host machine.

  config.vm.provider "virtualbox" do |vb|

    vb.name = "ubuntu-dev" # vm name on virtual box list
    vb.memory = "1024"
    vb.cpus = 1
  end

  config.vm.hostname = "ubuntu-dev-hostname" # vm hostname
end