variable "rds_type" {}
variable "rds_engine" {}
variable "rds_engine_version" {}
variable "db_password" {}
variable "db_username" {}
variable "rds_storage" {}
variable "sg_rds_id" {}
variable "private_subnets" {}
variable "public_subnets" {}
