---
- hosts: web
  become: yes
  tasks:
    - name: install packages
      apt:
        name: '{{ item }}'
        state: present
        update_cache: yes
      loop:
        - nginx
        - mc

    - name: add new group
      group:
        name: ansible
        state: present

    - name: add user
      user:
        name: ansible
        group: ansible
        shell: /bin/bash
        create_home: yes
        home: /home/ansible

    - name: Create ssh directory
      file:
        path: /home/ansible/.ssh
        state: directory
        recurse: yes
        owner: ansible
        group: ansible
        mode: '0700'

    - name: Create authorized_keys file
      become_user: root
      blockinfile:
        path: /home/ansible/.ssh/authorized_keys
        create: yes
        owner: ansible
        group: ansible
        mode: '0600'
        block: "{{lookup('ansible.builtin.file', '/vagrant/id_rsa.pub')}}"

    - name: Create file
      file:
        path: "/home/ansible/temp_file_{{lookup('pipe', 'date +%F_%T')}}"
        owner: ansible
        group: ansible
        state: touch

    - name: Add cronjob to delete temp files
      cron:
        name: cron job
        user: ansible
        minute: '0'
        hour: '22'
        job: 'rm -f /tmp/*'




