FROM nginx:stable-alpine
RUN wget https://www.tooplate.com/zip-templates/2123_simply_amazed.zip && \
    unzip 2123_simply_amazed.zip && \
    mv 2123_simply_amazed/* /usr/share/nginx/html/
EXPOSE 80 





