apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapp
  name: webapp
  namespace: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:      
      labels:
        app: webapp
    spec:
      containers:
      - image: dvsp-webapp:v1
        name: webapp  
        ports:
          - containerPort: 80      
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "nginx -version"
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "256Mi"
            cpu: "0.25"
          limits:
            memory: "512Mi"
            cpu: "0.5"

  
    





  