version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    privileged: true # gives access to resources of the host machine
    user: root
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - 8080
      - 50000 # with agents communication

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 4000:4000
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - jenkins

volumes:
  jenkins_home:


