- name: restart haproxy
  systemd:
    name: haproxy
    state: restarted
- name: restart monit
  systemd:
    name: monit
    state: restarted
- name: start and enable haproxy
  systemd:
    name: haproxy
    state: started
    enabled: true
- name: start and enable monit
  systemd:
    name: monit
    state: started
    enabled: true